---
title: "Lista II"
author: "Bento Rabello Botega (186461)"
format: pdf
---

## Inicialização

```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(SQLite(), "../datasets/me315.sqlite")
```

1.  

```{sql connection=con}
SELECT * FROM PRESERVE
ORDER BY ACRES
```

2.  

```{sql connection=con}
SELECT PNAME, FEE FROM PRESERVE WHERE STATE = 'MT'
ORDER BY PNAME DESC
```

3.  

```{sql connection=con}
SELECT FEE, ACRES FROM PRESERVE
ORDER BY FEE, ACRES
```

4.  

```{sql connection=con}
SELECT PNAME FROM PRESERVE WHERE STATE = 'AZ'
ORDER BY PNO
```

5.  

```{sql connection=con}
SELECT STATE, FEE, PNO FROM PRESERVE WHERE ACRES > 100
ORDER BY STATE DESC, FEE DESC, PNO
```

6.  

```{sql connection=con}
SELECT * FROM PRESERVE WHERE STATE >= 'M'
```

7.  

```{sql connection=con}
SELECT * FROM PRESERVE WHERE PNAME < "TATKON"
```

9.  

```{sql connection=con}
SELECT * FROM EMPLOYEE
ORDER BY ENAME
```

10. 

```{sql connection=con}
SELECT ENAME, SALARY FROM EMPLOYEE WHERE SALARY > 2000
ORDER BY SALARY DESC
```

11. 

```{sql connection=con}
SELECT DNO, ENO, ENAME FROM EMPLOYEE
ORDER BY DNO, ENO DESC
```
## Momento de compilação
```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```