---
title: "Lista VII"
author: "Bento Rabello Botega (186461)"
format: pdf
---

## Inicialização

```{r}
library(DBI)
library(RSQLite)
knitr::opts_chunk$set(max.print = Inf)
# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "../datasets/purchase.sqlite")
```

## Respostas

### 1.

```{sql connection=con}
SELECT PNO, SUM(COST) FROM PURCHASE
GROUP BY PNO
```

### 2.

```{sql connection=con}
SELECT ENO, SUM(COST) FROM PURCHASE
GROUP BY ENO
```

### 3.

```{sql connection=con}
SELECT PJNO, SNO, SUM(COST) FROM PURCHASE
GROUP BY PJNO, SNO
ORDER BY PJNO, SNO
```

### 4.

```{sql connection=con}
SELECT PNO, SNO, SUM(COST) FROM PURCHASE
GROUP BY PNO, SNO
ORDER BY PNO, SNO
```

### 5.

```{sql connection=con}
SELECT PJNO, ENO, SNO, SUM(COST) FROM PURCHASE
GROUP BY PJNO, ENO, SNO
ORDER BY PJNO, ENO, SNO
```
### 6.

```{sql connection=con}
SELECT PNO, SNO, ENO, SUM(COST) FROM PURCHASE
GROUP BY PNO, SNO, ENO 
ORDER BY PNO, SNO, ENO
```

### 7.

```{sql connection=con}
SELECT PJNO, ENO, SNO, SUM(COST) FROM PURCHASE
WHERE PJNO != "PJ2"
GROUP BY PJNO, ENO, SNO
```

### 8.

```{sql connection=con}
SELECT PNO, SNO, ENO, SUM(COST) FROM PURCHASE
GROUP BY PNO, SNO, ENO
HAVING SUM(COST) >= 2000
```

## Momento de compilação

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
