---
title: "Laboratório VII"
author: "Bento Rabello Botega (186461)"
format: pdf
---

## 1. 

```{r}
library(RSQLite)
conn <- dbConnect(SQLite(), "../datasets/uwmadison.sqlite3")
```

## 2.

```{r}
dbGetQuery(conn, paste(
  "SELECT COUNT(DISTINCT instructors.name) FROM subjects",
  "INNER JOIN subject_memberships ON subject_memberships.subject_code=subjects.code",
  "INNER JOIN sections ON sections.course_offering_uuid=subject_memberships.course_offering_uuid",
  "INNER JOIN teachings ON teachings.section_uuid=sections.uuid",
  "INNER JOIN instructors ON instructors.id=teachings.instructor_id",
  "WHERE subjects.abbreviation='STAT'"
))

dbGetQuery(conn, paste(
  "SELECT DISTINCT instructors.name FROM subjects",
  "INNER JOIN subject_memberships ON subject_memberships.subject_code=subjects.code",
  "INNER JOIN sections ON sections.course_offering_uuid=subject_memberships.course_offering_uuid",
  "INNER JOIN teachings ON teachings.section_uuid=sections.uuid",
  "INNER JOIN instructors ON instructors.id=teachings.instructor_id",
  "WHERE subjects.abbreviation='STAT'"
))
```

## 3.

```{r}
# Professor mais difícil:
dbGetQuery(conn, "
  SELECT 
    instructors.name, 
    SUM(
      COALESCE(a_count, 0) * 4 + 
      COALESCE(ab_count, 0) * 3.5 + 
      COALESCE(b_count, 0) * 3 + 
      COALESCE(bc_count, 0) * 2.5 + 
      COALESCE(c_count, 0) * 2 + 
      COALESCE(d_count, 0) * 1 + 
      COALESCE(f_count, 0) * 0
    ) / 
    CAST(
      SUM(
        COALESCE(a_count, 0) + 
        COALESCE(ab_count, 0) + 
        COALESCE(b_count, 0) + 
        COALESCE(bc_count, 0) + 
        COALESCE(c_count, 0) + 
        COALESCE(d_count, 0) + 
        COALESCE(f_count, 0)
      ) AS real
    ) AS mean_gpa
  FROM subjects
  INNER JOIN subject_memberships ON subject_memberships.subject_code = subjects.code
  INNER JOIN sections ON sections.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN grade_distributions ON grade_distributions.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN teachings ON teachings.section_uuid = sections.uuid
  INNER JOIN instructors ON instructors.id = teachings.instructor_id
  WHERE subjects.abbreviation = 'STAT'
  GROUP BY instructors.name
  HAVING SUM(COALESCE(a_count, 0) + COALESCE(ab_count, 0) + COALESCE(b_count, 0) + COALESCE(bc_count, 0) + COALESCE(c_count, 0) + COALESCE(d_count, 0) + COALESCE(f_count, 0)) > 0
  ORDER BY mean_gpa
  LIMIT 1
")

# Professor mais fácil:
dbGetQuery(conn, "
  SELECT 
    instructors.name, 
    SUM(
      COALESCE(a_count, 0) * 4 + 
      COALESCE(ab_count, 0) * 3.5 + 
      COALESCE(b_count, 0) * 3 + 
      COALESCE(bc_count, 0) * 2.5 + 
      COALESCE(c_count, 0) * 2 + 
      COALESCE(d_count, 0) * 1 + 
      COALESCE(f_count, 0) * 0
    ) / 
    CAST(
      SUM(
        COALESCE(a_count, 0) + 
        COALESCE(ab_count, 0) + 
        COALESCE(b_count, 0) + 
        COALESCE(bc_count, 0) + 
        COALESCE(c_count, 0) + 
        COALESCE(d_count, 0) + 
        COALESCE(f_count, 0)
      ) AS real
    ) AS mean_gpa
  FROM subjects
  INNER JOIN subject_memberships ON subject_memberships.subject_code = subjects.code
  INNER JOIN sections ON sections.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN grade_distributions ON grade_distributions.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN teachings ON teachings.section_uuid = sections.uuid
  INNER JOIN instructors ON instructors.id = teachings.instructor_id
  WHERE subjects.abbreviation = 'STAT'
  GROUP BY instructors.name
  HAVING SUM(COALESCE(a_count, 0) + COALESCE(ab_count, 0) + COALESCE(b_count, 0) + COALESCE(bc_count, 0) + COALESCE(c_count, 0) + COALESCE(d_count, 0) + COALESCE(f_count, 0)) > 0
  ORDER BY mean_gpa DESC
  LIMIT 1
")

# Matéria mais difícil:
dbGetQuery(conn, "
  SELECT 
    course_offerings.name, 
    SUM(
      COALESCE(a_count, 0) * 4 + 
      COALESCE(ab_count, 0) * 3.5 + 
      COALESCE(b_count, 0) * 3 + 
      COALESCE(bc_count, 0) * 2.5 + 
      COALESCE(c_count, 0) * 2 + 
      COALESCE(d_count, 0) * 1 + 
      COALESCE(f_count, 0) * 0
    ) / 
    CAST(
      SUM(
        COALESCE(a_count, 0) + 
        COALESCE(ab_count, 0) + 
        COALESCE(b_count, 0) + 
        COALESCE(bc_count, 0) + 
        COALESCE(c_count, 0) + 
        COALESCE(d_count, 0) + 
        COALESCE(f_count, 0)
      ) AS real
    ) AS mean_gpa
  FROM subjects
  INNER JOIN subject_memberships ON subject_memberships.subject_code = subjects.code
  INNER JOIN sections ON sections.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN grade_distributions ON grade_distributions.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN teachings ON teachings.section_uuid = sections.uuid
  INNER JOIN instructors ON instructors.id = teachings.instructor_id
  INNER JOIN course_offerings ON course_offerings.uuid=grade_distributions.course_offering_uuid
  WHERE subjects.abbreviation = 'STAT'
  GROUP BY course_offerings.name
  HAVING SUM(COALESCE(a_count, 0) + COALESCE(ab_count, 0) + COALESCE(b_count, 0) + COALESCE(bc_count, 0) + COALESCE(c_count, 0) + COALESCE(d_count, 0) + COALESCE(f_count, 0)) > 0
  ORDER BY mean_gpa 
  LIMIT 1
")

# Matéria mais fácil:
dbGetQuery(conn, "
  SELECT 
    course_offerings.name, 
    SUM(
      COALESCE(a_count, 0) * 4 + 
      COALESCE(ab_count, 0) * 3.5 + 
      COALESCE(b_count, 0) * 3 + 
      COALESCE(bc_count, 0) * 2.5 + 
      COALESCE(c_count, 0) * 2 + 
      COALESCE(d_count, 0) * 1 + 
      COALESCE(f_count, 0) * 0
    ) / 
    CAST(
      SUM(
        COALESCE(a_count, 0) + 
        COALESCE(ab_count, 0) + 
        COALESCE(b_count, 0) + 
        COALESCE(bc_count, 0) + 
        COALESCE(c_count, 0) + 
        COALESCE(d_count, 0) + 
        COALESCE(f_count, 0)
      ) AS real
    ) AS mean_gpa
  FROM subjects
  INNER JOIN subject_memberships ON subject_memberships.subject_code = subjects.code
  INNER JOIN sections ON sections.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN grade_distributions ON grade_distributions.course_offering_uuid = subject_memberships.course_offering_uuid
  INNER JOIN teachings ON teachings.section_uuid = sections.uuid
  INNER JOIN instructors ON instructors.id = teachings.instructor_id
  INNER JOIN course_offerings ON course_offerings.uuid=grade_distributions.course_offering_uuid
  WHERE subjects.abbreviation = 'STAT'
  GROUP BY course_offerings.name
  HAVING SUM(COALESCE(a_count, 0) + COALESCE(ab_count, 0) + COALESCE(b_count, 0) + COALESCE(bc_count, 0) + COALESCE(c_count, 0) + COALESCE(d_count, 0) + COALESCE(f_count, 0)) > 0
  ORDER BY mean_gpa DESC
  LIMIT 1
")
```

## 4.

```{r}
dbDisconnect(conn)
```

## Momento de compilação

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
